config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
    end
  end
  resources :gifts, param: :guid, only: [:update, :new, :create] do
    member do
      get 'convert'
    end
    collection do
      get 'exists'
      get 'thanks'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'add_favorite/:nonprofit_id', to: redirect('/subscribers/%{guid}/favorites/%{nonprofit_id}/add')
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end

    resources :favorites,     controller: 'subscriber/favorites',
                              as: :favorites,
                              only: [:index, :destroy, :create] do

      get 'add',          action: :create, as: :add, on: :member
    end
  end

  resources :newsletters do
    get :preview, on: :collection
  end
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users

  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  get  'donate',           to: 'donors#new',         as: :donate
  post 'donate',           to: 'donors#create'
  get  'gift',             to: 'gifts#new',          as: :gift_page
  post 'gift',             to: 'gifts#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"
  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers do
      member do
        put :resend_newsletter
      end
    end
    resources :stats
    resources :payouts, only: [:index, :create]
    resources :newsletters do
      member do
        get :preview
        post :send_preview
        get :donor_generated
        get :subscriber_generated
      end
    end
  end
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  belongs_to :gift
  belongs_to :subscriber, touch: true # (adding the 'validate' option causes a 2x :guid uniq validation in donor_test???) , validate: true # inseparable from the donor -- don't delete or detach
  has_many   :donations

  has_many   :cards, class_name: 'DonorCard'
  has_one    :card, -> { DonorCard.active }, class_name: 'DonorCard', inverse_of: :donor

  has_many   :nonprofits_donated_to,
             -> { order(featured_on: :desc) },
             through: :donations,
             source: :donated_nonprofits

  accepts_nested_attributes_for :gift
  accepts_nested_attributes_for :card
  accepts_nested_attributes_for :subscriber

  validates :subscriber, uniqueness: true, presence: true
  validates :guid, uniqueness: true, if: :guid_changed?

  scope :active,    -> { where(finished_on: nil, failed_at: nil) }
  scope :inactive,  -> { where("finished_on <= ? OR failed_at IS NOT NULL", Date.today) }
  scope :cancelled, -> { where.not(cancelled_at: nil) }
  scope :failed,    -> { where.not(failed_at: nil) }
  # should be mutually exclusive from Subscriber#for_daily_newsletter
  scope :for_daily_newsletter, -> { active.subscribed }
  scope :subscribed,        -> { joins(:subscriber).merge(Subscriber.active) }
  scope :unsubscribed,      -> { joins(:subscriber).merge(Subscriber.inactive) }
  scope :with_public_names, -> { where.not(public_name: ["", nil]) }

  STRIPE_FIELDS = [
    :stripe_token
  ]

  attr_accessor *STRIPE_FIELDS

  audited

  def stripe?; stripe_customer_id.present?; end
  def nfg?; nfg_donor_token.present?; end

  # # Get all the donors that have a donation to this nonprofit
  scope :for_nonprofit, ->(n) {
    joins(donations: [:nonprofits]).where("nonprofits.id = ?", n.id)
  }


  def to_param
    subscriber.try(:guid)
  end

  def has_duplicates?
    nonprofit_ids = donations.flat_map { |d| d.donation_nonprofits.pluck(:nonprofit_id) }
    nonprofit_ids.size != nonprofit_ids.uniq.size
  end

  def self.check_for_duplicate_donations
    donor_ids = Donor.all.select(&:has_duplicates?).map(&:id)
    AdminMailer.duplicate_donations(donor_ids).deliver if donor_ids.present?
  end

  def self.find_by_param(val)
    where(id: val).first || find(val)
  end

  # Regularly check/nullify donors who have left their active period (>30 days
  # after their last charge, aka after their last daily $1 donation).
  # TODO currently expired gifts will fail and the donors will be marked as "failed"
  # so they shouldn't get the donor newsletter -- should we instead run a task
  # like this one on finished gifts so they're marked as finished donors? We'd have
  # to remember to re-"start" them too once Gift#convert_to_recipient! (similar to Donor#uncancel!).
  def self.finish_cancelled_donors
    Donor.active.cancelled.each do |donor|
      last_donation = donor.last_executed_donation
      if last_donation.blank? || Time.now > (last_donation.scheduled_at + 30.days)
        donor.card.try(:deactivate!)
        donor.update_attribute(:finished_on, Time.zone.now.to_date)
      end
    end
  end

  def active_subscriber?
    subscriber.try(:active?)
  end

  def cancelled?
    cancelled_at.present?
  end

  def active?
    !inactive?
  end

  def failed?
    failed_at.present?
  end

  def inactive?
    failed? || finished_on.present?
  end

  def last_executed_donation
    donations.executed.order("executed_at DESC").first
  end

  def cancel!(notify_donor: true)
    return if cancelled?

    transaction do
      donations.pending.update_all(cancelled_at: Time.now)
      self.cancelled_at = Time.now
      self.uncancelled_at = nil
      save!
      SendCancelledJob.new(self.id).save if notify_donor
    end
  end

  def uncancel!
    return unless cancelled?

    transaction do
      last_donation = donations.executed.last
      next_donation_at = [
        (30.days.since(last_donation.scheduled_at) if last_donation), # for cancelled/active donors
        finished_on,  # for cancelled/inactive donors (this *should* actually be the same as the above, if finished_on is present)
        Time.now      # bare minimum
      ].compact.max

      # NB schedule at 12am, so the newsletter at 8am has the day's correct donor count
      donations.build(scheduled_at: next_donation_at.beginning_of_day)
      self.uncancelled_at = Time.now
      self.finished_on  = nil
      self.cancelled_at = nil
      save!
      SendUncancelledJob.new(self.id).save
    end
  end

  def nfg_history
    NetworkForGood::CreditCard.get_donor_donation_history(self)
  end

  private

  after_create :schedule_first_donation
  def schedule_first_donation
    donations.create(scheduled_at: Time.now)
  end

  before_validation :preprocess, on: :create
  def preprocess
    self.started_on                 = Time.zone.now.to_date
    self.guid                       = guid.presence || SecureRandom.hex(16)

    # If there's a subscriber that hasn't donated with the same email, attach
    # them to this donor. (If there's a subscriber with a donor and the same email,
    # then the subscriber's email uniqueness validation should fire, otherwise).
    if gift.present?
      if s = Subscriber.without_donor.where(email: subscriber.email).first
        name = subscriber.name
        self.subscriber = s
        subscriber.name = name # if they aren't donating yet, they shouldn't have a name yet
      end
    else
      if s = Subscriber.without_donor.where(email: card.email).first
        self.subscriber = s
      end
    end

    build_subscriber if subscriber.blank?

    if gift.blank?
      subscriber.name                 = card.name       if subscriber.name.blank? # populate the subscriber's name (means they existed already)
      subscriber.email                = card.email      if subscriber.email.blank?
      subscriber.ip_address           = card.ip_address if subscriber.ip_address.blank?
    end
  end
end

app/controllers/admin/donors_controller.rb
class Admin::DonorsController < Admin::BaseController
  before_filter :find_donor, only: [:show]

  def index
    @q = Donor.search(params[:q])
    @donors = @q.result(distinct: true).includes(:card, :subscriber)
  end

  def find_donor
    @donor = Donor.find_by_param(params[:id])
  end

  def show
  end

end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_filter :authenticate_user!, only: :index
  before_filter :admin_required, only: :index

  before_filter :require_donor, only: [:cancel, :uncancel, :edit, :update]
  before_filter :initialize_donor, only: [:new, :create, :new_gift, :create_gift]

  respond_to :html, except: [:exists, :fetch_state_by_zip, :map]
  respond_to :json, only: [:exists, :fetch_state_by_zip, :map]

  def index
    @donors = Donor.active.order("created_at ASC")
    @subscriber = Subscriber.new
  end

  def new
    @require_stripe_js = true
    @hide_header = true
    @hide_footer = true

    if params[:email].present?
      @subscriber = Subscriber.where(email: params[:email].to_s).first_or_initialize
      @donor.subscriber = @subscriber
      @donor.build_card(email: @subscriber.email)
    end

    respond_with(@donor)
  end

  def create
    @require_stripe_js = true
    @hide_header = true
    @hide_footer = true

    @donor.attributes      = donor_params
    @donor.card.ip_address = request.ip

    @donor.card.stripe_token = params[:stripeToken] if params["stripeToken"].present?

    Donor.transaction do
      @donor.save!

      # Have the first donation execute immediately (instead of the 15-minute
      # cron interval) so it seems more immediate.
      @donor.donations.pending.first.lock_and_execute!
      session[:thanks] = @donor.subscriber.first_name
      redirect_to thanks_donors_url
    end
 rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => e
    render :new
  end

  # "Change Billing Details"
  def edit
    @require_stripe_js = true
    @new_card = current_donor.cards.new
  end

  # TODO cleanup
  def update
    @require_stripe_js = true
    @new_card            = DonorCard.new(donor_card_params[:card_attributes])
    @new_card.ip_address = request.ip
    @new_card.is_active  = false
    @new_card.donor      = current_donor # TODO inverse_of?
    @new_card.stripe_token = params[:stripeToken]
    @new_card.stripe_email = params[:stripeEmail]
    @new_card.save!

    was_failed = current_donor.failed?

    current_donor.reload
    current_donor.cards.active.where.not(id: @new_card.id).each(&:deactivate!)
    @new_card.activate!

    # If they're fixing their card, try the failed donation again.
    if donation = current_donor.donations.failed.first
      donation.fix!
    end

    if was_failed
      flash[:notice] = "Thanks! We'll try it again now, and let you know by email."
    else
      flash[:notice] = "Thanks! We'll use this card from here on out."
    end
    redirect_to root_url
  rescue ActiveRecord::RecordInvalid => e
    render :edit
  end

  def cancel
    @creds = params[:donor_verification]

    # TODO test the @auth_method thing -- this is so users don't have to 2x auth
    #  when going to cancel via website (instead of email)
    if auth_method == :card || current_donor.card.valid_credentials?(@creds[:last_4], @creds[:exp_month], @creds[:exp_year])
      current_donor.cancel!
      render json: {success: "Thanks! Your future donations have been cancelled."}
    else
      render json: {error: "Sorry, those were not the correct credentials!"}
    end
  end

  def uncancel
    @creds = params[:donor_verification]

    # TODO test the @auth_method thing -- this is so users don't have to 2x auth
    #  when going to cancel via website (instead of email)
    if auth_method == :card || current_donor.card.valid_credentials?(@creds[:last_4], @creds[:exp_month], @creds[:exp_year])
      current_donor.uncancel!
      render json: {success: "Thanks, you've signed up to start donating again!"}
    else
      render json: {error: "Sorry, those were not the correct credentials!"}
    end
  end

  # TODO throttle this?
  def exists
    @donor = Subscriber.where(email: params[:email].to_s).first.try(:donor)

    # TODO other way for gifts here
    if @donor && (@donor.gift.nil? || @donor.gift.converted_to_recipient?)
      if @donor.active?
        if @donor.cancelled?
          msg = "You've recently canceled. To start donating again, or otherwise manage your account,"
        else
          msg = "You're already a donor. To manage your account"
        end
      else
        msg = "You've recently canceled. To start donating again, or otherwise manage your account,"
      end

      json = { success: true, message: msg }
    else
      json = { success: false }
    end

    respond_to do |format|
      format.json do
        render json: json
      end
    end
  end

  # Verify the donor's info, and pass them on to status page (?)
  def verify
    if verify_donor
      json = { success: true, location: subscriber_url(current_subscriber) }
    else
      json = { success: false, message: "We couldn't verify this account. Please check your info." }
    end

    respond_to do |format|
      format.json do
        render json: json
      end
    end
  end

  def thanks
    @hide_header = true
    @hide_footer = true

    @name = session['thanks']
    redirect_to root_url unless @name = session.delete(:thanks)
  end

  def fetch_state_by_zip
    @json =
      if params[:zip] && params[:zip] =~ /\A\d\d\d\d\d\z/
        city, state = params[:zip].to_region.split(",")
        {city: city.strip, state: state.strip}
      else
        {}
      end
    respond_with(@json)
  end

  def map
    @donors = Donor.active
    @json = []
    @donors.each { |d| @json.push(:latitude => d.subscriber.latitude, :longitude => d.subscriber.longitude, :city => d.subscriber.city) }
    respond_with(@json)
  end

  private
  def donor_params
    params.require(:donor).permit(
      :add_fee, :public_name, {card_attributes: [:name, :email]}
    )
  end

  def donor_card_params
    params.require(:donor).permit(
      card_attributes: [:name, :email]
    )
  end
end

app/views/donors/_authenticate_form.html.erb
<div id="authenticate-overlay" class="modal-overlay">
  <div class="modal-bg modal-overlay-dark js-modal-overlay-close"></div>
  <div class="modal-content mobile-table full-height">
    <div class="mobile-table-cell">
      <div class="interior js-interior dropshadow relative centered-container margin-auto p4">
        <a href="#" class="js-modal-overlay-close modal-overlay-close"><%= image_tag "x.svg", width: 20, height: 20 %></a>
        <%= render partial: "donors/verify_form" %>
      </div>
    </div>
  </div>
</div>

app/views/donors/_card_fields.html.erb
<% f = form_builder # the donate form builder object %>
<% card = defined?(card) && card.present? ? card : (f.object.card || DonorCard.new) %>

<%= f.fields_for(:card, card) do |c| %>

  <div class="field mb1">
      <% unless Rails.env.production? -%>
        <span id="donate_test_data_button" style="text-decoration: underline; cursor: pointer;" class="right small">Use Test Data</span>
      <% end %>
      <%= c.label :email, "Your Email #{error_tooltip_for(c.object, :email)}".html_safe %>
      <%= c.text_field :email, autocompletetype: "email", class: "full-width", tabindex: 1 %>
  </div>

  <div class="field mb1">
    <%= c.label :name, "Full name #{error_tooltip_for(c.object, :name)}".html_safe %>
    <%= c.text_field :name, autocompletetype: "given-name", class: "full-width", tabindex: 2 %>
  </div>

  <div class="field mb1">
    <div class="clearfix">
      <%= c.label :card_number, "Card number #{error_tooltip_for(c.object, :card_number)}".html_safe, class: "left" %>
      <div class="right">
        <%= image_tag "checkout/icon-cc-visa.png", width: "35" %>
        <%= image_tag "checkout/icon-cc-amex.png", width: "35" %>
        <%= image_tag "checkout/icon-cc-mastercard.png", width: "35" %>
      </div>
    </div>
    <%= c.text_field :card_number, autocomplete: "off", class: "full-width", tabindex: 3 %>
  </div>


  <div class="field clearfix bottom-padding-fix">
    <div class="left">
      <%= c.label :exp_month, "Expiration date #{error_tooltip_for(c.object, :exp_month)}".html_safe, class: "clearfix" %>
      <div class="select-container mr1 left">
        <%= c.select :exp_month, (1..12).to_a, {}, autocomplete: "off", tabindex: 4 %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
      <div class="select-container mr2 left">
        <%= c.select :exp_year, (Time.zone.now.year..10.years.from_now.year), {}, autocomplete: "off", tabindex: 5 %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
    </div>
    <div class="clearfix relative bottom-padding-fix pl3 mobile-no-padding">
      <%= c.label(:csc) do %>
        <%= "CVV #{error_tooltip_for(c.object, :csc)}".html_safe %>
      <% end %>
      <%= c.text_field :csc, class: "full-width", autocomplete: "off", size: 4, tabindex: 6 %>
    </div>
  </div>


  <div class="field">
    <%= c.label :address1, "Billing address #{error_tooltip_for(c.object, :address1)}".html_safe %>
    <%= c.text_field :address1, class: "full-width", tabindex: 7 %>
  </div>

  <div class="field">
    <%= c.label :city, "City #{error_tooltip_for(c.object, :city)}".html_safe %>
    <%= c.text_field :city, class: "full-width", tabindex: 8 %>
  </div>

  <div class="field">
    <%= c.label :country, "Country #{error_tooltip_for(c.object, :country)}".html_safe %>
    <div class="select-container full-width">
      <%= c.select :country, options_for_select(CARMEN_COUNTRY_OPTIONS, "US"), {}, tabindex: 9 %>
      <span class="ss-icon ss-dropdown"></span>
    </div>
  </div>

  <div class="clearfix field">
    <div class="right pl1 bottom-padding-fix" style="width: 163px;">
      <%= c.label :zip, "Zip/post code #{error_tooltip_for(c.object, :zip)}".html_safe %>
      <%= c.text_field :zip, class: "full-width", autocompletetype: "postal-code", tabindex: 11 %>
    </div>
    <div class="clearfix bottom-padding-fix">
      <%= c.label :state, "State/region #{error_tooltip_for(c.object, :state)}".html_safe %>
      <%= c.text_field :state, id: "donor_card_attributes_region", class: "full-width", tabindex: 10 %>
      <div class="select-container full-width">
        <%= c.select :state, [["Select", nil]] + UNITED_STATES, {}, tabindex: 10  %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
    </div>
  </div>

<% end -%>

app/views/donors/_form.html.erb
<p id="existing_donor_message" style="display: none;">
  <span class="highlight"></span>&nbsp;<%= link_to "click here", "#authenticate-overlay", class: "js-modal-overlay-open inline-block mr1 grey" -%>
</p>

<section id="other">
  <%= render "donors/stripe_card_fields", form_builder: form_builder %>
</section>

<section id="form_footer" class="clear">
  <div class="checkbox pt1 pb3 relative">
    <%= form_builder.check_box :add_fee, {tabindex: 12}, "1", "0" %>
    <%= form_builder.label(:add_fee, class: "clearfix") do %>
      <%= "Give an extra $%0.2f per month to cover credit card fees." % stripe_fee_amount  %>
      <a class="<%= form_builder.object.gift.present? ? 'tooltip-se' : 'tooltip' %> tooltop-offset tablet-hide" title="<div style='width: 300px'>Stripe charges a processing fee. Adding <%= "$%0.2f" % stripe_fee_amount %> per month to your donation allows a full $30 to go to nonprofits.</div>"><span class="ss-icon ss-help"></span></a>
    <% end %>
  </div>

  <%= form_builder.submit "Donate!", class: "button-solid button-green button-big full-width", tabindex: 13 %>

</section>

app/views/donors/_form_container.html.erb
<% @donor ||= Donor.new.tap { |d| d.started_on = Time.zone.now.to_date } %>

<%= render 'donors/authenticate_form' %>

<section class="donate-form bg-cover bg-grey" style="background-image: url(<%= asset_path 'blurred-bg.jpg' %>);">

  <div class="pt2 pb2 mobile-hide"></div>

  <div class="centered-container margin-auto py6 pl4 pr4 bg-white">
    <div class="table mb2">
      <div class="table-cell">
        <%= render "modules/logo_link", theme: :dark %>
      </div>
      <div class="table-cell align-right">
        <%= link_to gift_page_url(ref: default_ref_tag), class: "no-decoration small bold" do %>
          <%= image_tag "gift.svg", width: 15, class: "inline-block", style: "margin-right: 5px;" %>
          <!-- Give as a gift -->
        <% end %>
      </div>
    </div>
    <p class="mb1">
      Donors are charged monthly, $30 every 30 days. It's easy to cancel, and 100% US tax-deductible.
    </p>
    <p class="mb1">
      <b class="green">Join <%= donor_count %> others!</b>
    </p>

    <%= form_for @donor, as: :donor, url: "/donate", html: {autocomplete: "on", class: "pt2 pb4"} do |d| %>
      <%= render "donors/form", form_builder: d %>
    <% end -%>

    <footer>
      <div class="flag">
        <div class="flag-body small">
          <%= link_to "Terms & Privacy", legal_path(ref: default_ref_tag), class: "mr1 inline-block" %>
          <%= link_to "FAQ", faq_path(ref: default_ref_tag), class: "inline-block" %>
        </div>
        <div class="flag-img align-right">
          <% if false # enable if you're using NFG as a processor -%>
          <%= image_tag "checkout/powered-by-nfg.png", alt: "Powered by Network for Good", width: "130", class: "tablet-hide inline-block relative tooltip", title: "<div style='width: 400px;'>#{render('donors/nfg_tooltip') }</div>" %>
          <%= image_tag "checkout/powered-by-nfg.png", alt: "Powered by Network for Good", width: "130", class: "tablet-block hide inline-block relative tooltip" %>
          <a href='http://www1.networkforgood.org/donationfaq' target='_blank'>Questions about NFG?</a>
          <% end -%>
        </div>
    </footer>
  </div>

  <div class="pt2 pb2 mobile-hide"></div>

</section>

app/views/donors/_index.html.erb
<h3>LATEST DONOR</h3>

<h4><%= @latest_donor %> <img src="/images/hand.png" /><span><strong>No.</strong><%= donor_count %></span></h4>

<p id="more_donors">
  <a href=""><img src="/images/more_donors_link.png" alt="-------->" />View all donors</a>
</p>

app/views/donors/_nfg_tooltip.html.erb
Network For Good, Inc processes all credit cards, and collect all donations for <%= CONFIG[:name] %>. They then disburse funds directly to the featured nonprofits on a monthly basis. To limit solicitations, your personal info won’t be forwarded to each nonprofit.
<br /><br />
Network for Good, Inc. is a registered 501c3 organization, allowing US tax deductions for US donors as applicable. They are accredited by the Better Business Bureau Wise Giving Alliance and meet all 20 of its standards for charity accountability. Since 2001, they’ve processed over $1 billion for over 100,000 nonprofits.
<br /><br />
Network For Good takes a processing fee (4%). But we offer donors the option to pay a little extra each month to cover the processing fee.
<br /><br />
Learn more at networkforgood.org

app/views/donors/_verify_form.html.erb
<% form_id ||= "verify_donor" %>

<%= form_tag verify_donors_url(format: :json), method: :put, remote: true, id: form_id, class: "verify_donor_form" do %>
  <p class="message"></p>

  <p>To manage your account, please enter your email:</p>

  <div class="field">
    <%= text_field_tag 'donor_verification[email]', nil, placeholder: "Email", class: "js-focus-on-open full-width", tabindex: 1 %>
  </div>

  <p class="instructions">Next, please enter the last 4 digits and expiration of the credit card used:</p>

  <%= render "donors/verify_billing_fields" %>

  <%= submit_tag "Manage account", class: "button-solid button-green button-big" , id: "manage-account-button", tabindex: 5 %>
<% end -%>

app/views/donors/cancelled.html.erb
<section class="table full-width full-height">
  <section class="centered table-cell align-middle">
    <div class="interior inline-block">

      <p class="big_type">
        Future donations are now canceled. We’ll send you an email now to confirm.
        If this was a rash decision and you’ve changed your mind,
        <%= link_to "click here", subscriber_url(@donor.subscriber.guid, auth: @donor.subscriber.auth_token) %><br />
        :)
      </p>

    </div>
  </section>
</section>

app/views/donors/thanks.html.erb
<%= content_for :extra_head do %>
<meta property="og:description" content="I just joined <%= donor_count %> others and signed up to give a dollar a day." />
<% end %>

<section class="table full-height">
  <div class="table-cell full-height bg-cover tablet-hide p6 centered" style="background-size: auto 120%; background-position: center center; background-image: url(<%= asset_path 'checkout/thanks.jpg' %>);">
    <%= link_to image_tag("logo.png", width: "140", class: "dark"), root_path(ref: default_ref_tag), class: "mb2 close inline-block" %>
    <h2 class="white">Thanks <%= @name %>, you're awesome!</h2>
  </div>
  <div class="hide tablet-block bg-cover mobile-hide p6 centered" style="background-position: center center; background-image: url(<%= asset_path 'checkout/thanks.jpg' %>);">
    <%= link_to image_tag("logo.png", width: "140", class: "dark"), root_path(ref: default_ref_tag), class: "mb2 close inline-block" %>
    <h2 class="white">Thanks <%= @name %>, you're awesome!</h2>
  </div>
  <div class="table-cell min-height-100 bg-white p6">
    <h3 class="green mb3">Can you spare a tweet?</h3>

    <p>Thanks for becoming a donor!</p>

    <p><%= CONFIG[:name] %> is fueled by the support of its community, so tell the world:</p>

    <div class="border-left-3px-green p2 mb4">
      <p class="quote no-margin">I just joined <%= donor_count %> donors giving a dollar a day to amazing nonprofits!</p>
    </div>

    <ul class="clearfix mb2">
      <li class="inline-block mobile-block">

        <%= link_to(share_url(url: "https://twitter.com/share?text=I%20just%20joined%20#{donor_count}%20donors%20giving%20a%20dollar%20a%20day%20to%20amazing%20nonprofits!&url=#{root_url}"), target: "_blank", class: "twitter button-solid button-big button-twitter mobile-block centered") do %>
          <span class="ss-icon ss-social ss-twitter"></span>
          Tweet
        <% end %>
      </li>
      <li class="inline-block ml1 mobile-no-margin mobile-block">
        <%= link_to(share_url(url: "http://www.facebook.com/dialog/feed?display=popup&redirect_uri=#{URI.escape(root_url)}&app_id=#{FACEBOOK[:app_id]}&link=#{URI.escape(root_url)}"), target: "_blank",class: "facebook button-solid button-big mobile-block button-facebook centered") do %>
          <span class="ss-icon ss-social ss-facebook"></span>
          Share
        <% end %>
      </li>
    </ul>

    <p>And keep an eye on your inbox &mdash; today’s nonprofit is on its way.</p>

  </div>
</section>