config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
    end
  end
  resources :gifts, param: :guid, only: [:update, :new, :create] do
    member do
      get 'convert'
    end
    collection do
      get 'exists'
      get 'thanks'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'add_favorite/:nonprofit_id', to: redirect('/subscribers/%{guid}/favorites/%{nonprofit_id}/add')
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end

    resources :favorites,     controller: 'subscriber/favorites',
                              as: :favorites,
                              only: [:index, :destroy, :create] do

      get 'add',          action: :create, as: :add, on: :member
    end
  end

  resources :newsletters do
    get :preview, on: :collection
  end
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users

  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  get  'donate',           to: 'donors#new',         as: :donate
  post 'donate',           to: 'donors#create'
  get  'gift',             to: 'gifts#new',          as: :gift_page
  post 'gift',             to: 'gifts#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"
  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers do
      member do
        put :resend_newsletter
      end
    end
    resources :stats
    resources :payouts, only: [:index, :create]
    resources :newsletters do
      member do
        get :preview
        post :send_preview
        get :donor_generated
        get :subscriber_generated
      end
    end
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_one  :donor # inseparable from the subscriber -- don't delete or deatch
  has_many :given_gifts, class_name: "Gift", foreign_key: "giver_subscriber_id"
  has_many :emails

  has_many :favorites,
           -> { order(created_at: :desc) }
  has_many :favorite_nonprofits,
           through: :favorites,
           source:  :nonprofit

  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9\*]+\.)+[a-z]{2,})\Z/i }
  validates :name, length: { minimum: 1, maximum: 100, allow_blank: true }
  validates :auth_token, presence: true, uniqueness: true
  validates :ip_address, presence: true
  validates :name, presence: { if: "donor.try(:gift).present?" } # require gift subscriber name to be there

  scope :active,   -> { where(unsubscribed_at: nil) }
  scope :inactive, -> { where.not(unsubscribed_at: nil) }

  # should be mutually exclusive from Donor#for_daily_newsletter
  scope :for_daily_newsletter, -> {
    active.
    joins("LEFT JOIN donors ON subscribers.id = donors.subscriber_id").
    where("donors.id IS NULL OR donors.finished_on < ?", Time.now).
    where("donors.failed_at IS NULL") # don't send *any* newsletters to failed donors
  }
  scope :without_donor, -> {
    joins("LEFT JOIN donors ON subscribers.id = donors.subscriber_id").
    where(donors: {id: nil})
  }

  accepts_nested_attributes_for :donor, update_only: true

  audited

  attr_accessor :resubscribing

  def active?
    unsubscribed_at.blank?
  end

  def active_donor?
    donor.try(:active?)
  end

  # This would be the case when we create a Subscriber as Gift#giver_subscriber...
  # we just need the record so they can manage their Status Page, but not necessarily
  # get the newsletter.
  def never_subscribed?
    subscribed_at && unsubscribed_at && subscribed_at.change(sec: 0) == unsubscribed_at.change(sec: 0)
  end

  def to_param
    guid
  end

  def donor?
    donor.present?
  end

  def first_name
    name.to_s.split_name.first
  end

  def unsubscribe!
    self.unsubscribed_at = Time.now
    save!
  end

  def resubscribe!
    self.unsubscribed_at = nil
    self.subscribed_at = Time.now
    save!
    SendFirstNewsletterJob.new(self.id).save
  end

  def set_location
    return if ip_address == "127.0.0.1"

    ip_address = ip_address.gsub(/[^0-9.]/, '')
    response = HTTPI.get "https://#{MAXMIND[:user_id]}:#{MAXMIND[:password]}@geoip.maxmind.com/geoip/v2.0/city/#{ip_address}"

    json = JSON.parse(response.body)

    Rails.logger.info "Maxmind response:"
    Rails.logger.info json.inspect

    raise "Maxmind error: #{json.inspect}" if json['error']

    if json["location"]
      self.latitude  = json["location"]["latitude"]
      self.longitude = json["location"]["longitude"]
    end
    self.city      = json['city']['names']['en'] if json['city']
    self.region    = json['subdivisions'][0]['names']['en'] if json['subdivisions']
    if json["country"]
      self.country   = json['country']['names']['en']
    elsif json["registered_country"]
      self.country   = json['registered_country']['names']['en']
    end

    self.save!
  end

  def to_mailgun_recipient
    return { self.email => self.slice(:guid, :auth_token).merge(name: self.first_name) }
  end

  after_commit :update_intercom
  def update_intercom
    SyncSubscriberDataToIntercomJob.new(self.id).save
  end

  private

  # Preprocess
  before_validation :preprocess, on: :create
  def preprocess
    self.subscribed_at       = Time.now
    self.guid              ||= SecureRandom.hex(16)
    self.auth_token        ||= SecureRandom.hex(32)
    true
  end

  after_create :send_first_newsletter
  def send_first_newsletter
    SendFirstNewsletterJob.new(self.id).save if active?
  end

  after_create :lookup_location
  def lookup_location
    SetSubscriberLocationJob.new(id).save if ip_address.present?
  end

  after_update :send_email_changed_notification, if: :email_changed?
  def send_email_changed_notification
    SendEmailChangedNotificationJob.new(id, email, email_was).save
  end
end

app/controllers/admin/subscribers_controller.rb
class Admin::SubscribersController < Admin::BaseController
  def index
    @q = Subscriber.includes(:donor).search(params[:q])
    @subscribers = @q.result(distinct: true)
  end

  def show
    @subscriber = Subscriber.find params[:id]
    @donor = @subscriber.donor
  end

  # Maybe someone entered the wrong email at first, changed it, and
  # requested us to resend the newsletter.
  def resend_newsletter
    @subscriber = Subscriber.find params[:id]
    @nonprofit = Nonprofit.find(params[:nonprofit_id])

    type = @subscriber.active_donor? ? "donor" : "subscriber"
    recipients = @subscriber.to_mailgun_recipient

    NewsletterMailer.batched_daily(type, @nonprofit.newsletter.id, recipients)
    email = @subscriber.emails.new(to: @subscriber.email,  newsletter: @nonprofit.newsletter, sent_at: Time.now, mailer: "NewsletterMailer", mailer_method: "daily_#{type}")
    email.save!(validate: false) # ugh, validation

    flash[:notice] = "Newsletter resent!"
    redirect_to admin_subscriber_url(@subscriber.id)
  end
end

app/controllers/subscriber/favorites_controller.rb
class Subscriber::FavoritesController < ApplicationController
  include SubscriberConcerns

  before_action :load_subscriber
  before_action -> { require_subscriber(@subscriber) }, except: [:index]

  def create
    begin
      @nonprofit = Nonprofit.find(params[:id])
      @favorites_diff = 0
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to subscriber_path(@subscriber), alert: t('favoriting.add.flash.error') }
        format.js   { render js: '', status: 400 }
      end
    else
      exists = @subscriber.favorite_nonprofits.where(id: @nonprofit.id).any?
      if !exists
        @subscriber.favorite_nonprofits << @nonprofit
        @favorites_diff = 1
      end
      respond_to do |format|
        format.js
        format.html {
          notice = exists ? t('favoriting.add.flash.redundant', name: @nonprofit.name) : t('favoriting.add.flash.success', name: @nonprofit.name)
          redirect_to subscriber_favorites_path(@subscriber), notice: notice
        }
      end
    end
  end

  def destroy
    begin
      @nonprofit = Nonprofit.find(params[:id])
      @favorites_diff = 0
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to subscriber_path(@subscriber), alert: t('favoriting.remove.flash.error') }
        format.js   { render js: '', status: 400 }
      end
    else
      exists = @subscriber.favorite_nonprofits.where(id: @nonprofit.id).any?
      if exists
        Favorite.where(subscriber_id: @subscriber.id, nonprofit_id: @nonprofit.id).destroy_all
        @favorites_diff = -1
      end
      respond_to do |format|
        format.js
        format.html {
          notice = exists ? t('favoriting.remove.flash.success', name: @nonprofit.name) : t('favoriting.remove.flash.redundant', name: @nonprofit.name)
          redirect_to subscriber_favorites_path(@subscriber), notice: notice
        }
      end
    end
  end

  def index

    if current_subscriber? && current_subscriber == @subscriber
      render :index
    else
      render :public, layout: "public"
    end

  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  before_action :load_subscriber,                       except: [:new, :create, :thanks]
  before_action -> { require_subscriber(@subscriber) }, except: [:new, :create, :thanks, :email_login, :favorites]

  respond_to :html
  respond_to :js, only: :create

  def show
    # redirect to self without params[:auth] to remove it from the url
    if params[:auth]
      redirect_to subscriber_path(current_subscriber)
    end
  end

  def donations
    @favorite_nonprofits_ids = @subscriber.favorite_nonprofits.pluck(:id)
  end

  def new
    @subscriber = Subscriber.new
    @hide_header = true
    @hide_footer = true
  end

  def create
    @subscriber               = Subscriber.inactive.where(email: subscriber_params[:email]).first_or_initialize(subscriber_params)
    @subscriber.ip_address    = request.ip
    @subscriber.resubscribing = true if @subscriber.persisted?
    set_subscriber_cookie(@subscriber, :signup)

    if @subscriber.save
      session[:thanks] = true
      if request.xhr?
        head 200
      else
        redirect_to thanks_subscribers_url
      end
    else
      if request.xhr?
        render text: "#{@subscriber.errors.full_messages.first}.", status: 400
      else
        render :new
      end
    end
  end

  def thanks
    @hide_header = true
    @hide_footer = true
    redirect_to root_url unless session.delete(:thanks)
  end

  def update
    @current_subscriber.attributes = subscriber_params

    if @current_subscriber.save
      redirect_to subscriber_url(@current_subscriber)
      flash[:notice] = "Your email has been updated"
    else
      render :show
    end
  end

  def unsubscribe
    @current_subscriber.unsubscribe!
    cookies[:unsubscribed] = true
    flash[:notice] = "You've been unsubscribed! Come back here if you change your mind."
    redirect_to subscriber_url(@current_subscriber)
  end

  def resubscribe
    @current_subscriber.resubscribe!
    cookies[:resubscribed] = true
    flash[:notice] = "You've been resubscribed!"

    redirect_to subscriber_url(@current_subscriber)
  end

  def email_login
    set_subscriber_cookie(@subscriber, :email)
    if params[:next] and params[:next] =~ /\A\/[^\/].*\z/
      redirect_to params[:next]
    else
      redirect_to subscriber_path(@subscriber)
    end
  end

  def logout
    unset_subscriber_cookie
    flash[:notice] = "You’ve logged out. See you soon!"
    redirect_to root_url
  end

  protected

  def subscriber_params
    params.require(:subscriber).permit(:name, :email)
  end

  def load_subscriber
    @subscriber = Subscriber.where(params.permit(:guid, :auth_token)).first or redirect_to root_url
  end

end

app/helpers/subscriber/favorites_helper.rb
module Subscriber::FavoritesHelper

  def render_favoriting_button nonprofit_id, status, options={}
    classes = []
    classes << (status ? 'is-on' : 'is-off')
    classes << options[:class] if options[:class].present?
    render partial: 'subscriber/favorites/button', locals: { nonprofit_id: nonprofit_id, classes: classes.join(" ") }
  end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/show/_become_a_donor.html.erb
<div class="hero-calendar py3 px2 mb2 mt4">
  <div class="flag">
    <div class="table-cell full-width pr2 pl2 py1 mobile-center">
      <p class="white no-margin"><%= pluralize(number_with_delimiter(donor_count), "donor") %> are supporting great nonprofits like this on <%= CONFIG[:name] %>.</p>
    </div>
    <div class="table-cell no-wrap py1 mobile-center">
      <%= link_to "Become a donor!", donate_url(email: current_subscriber.email), class: "button-solid button-white" %>
    </div>
  </div>
</div>

app/views/subscribers/show/_billing_details.html.erb
<%= link_to "Change billing details", resubscribe_subscriber_url(@current_subscriber), class: "js-form-link bold reset-button mr2 green", :'data-form-id' => "change-billing-details-form" %>

<%= form_tag "/", method: :put, id: "change-billing-details-form", style: "#{'display: none'}", class: "js-form mt4" do %>

  <% if auth_method != :card %>
    <p>To change billing details, please verify your credit card info:</p>

    <div class="row verification">
      <div class="col">
        <%= label :exp_month, "Credit card expiration", class: "small bold block mb1" %>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_month]', options_for_select((1..12).to_a) %>
        </div>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_year]', options_for_select((Time.zone.now.year..10.years.from_now.year)) %>
        </div>
      </div>
      <div class="col col-6 mobile-clear">
        <%= label :last_4, "Last four digits", class: "small bold block mb1" %>
        <%= text_field_tag 'donor_verification[last_4]', nil, placeholder: "Last 4 Digits", style: "width: 140px;", :autocomplete => "off" %>
        <a class="ss-icon ss-help tooltip relative" title="<div style='width: 300px'>The last 4 digits of the credit card you used for #{CONFIG[:name]}.</div>"></a>
      </div>
    </div>
  <% end %>

  <p class="error"></p>

  <%= submit_tag "Continue", class: "button-solid button-green" %>

<% end %>

app/views/subscribers/show/_cancel.html.erb
<%= link_to "Cancel future donations", cancel_donor_url(@current_subscriber), class: "js-form-link small bold red no-wrap", :'data-form-id' => "cancel-future-donations-form" %>

<%= form_tag cancel_donor_url(@current_subscriber), method: :put, id: "cancel-future-donations-form", style: "display: none", class: "js-form mt4" do %>

  <% if auth_method != :card %>
    <p>To cancel, please verify your credit card info:</p>

    <div class="row verification">
      <div class="col">
        <%= label :exp_month, "Credit card expiration", class: "small bold block mb1" %>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_month]', options_for_select((1..12).to_a) %>
          <span class="ss-icon ss-dropdown"></span>
        </div>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_year]', options_for_select((Time.zone.now.year..10.years.from_now.year)) %>
          <span class="ss-icon ss-dropdown"></span>
        </div>
      </div>
      <div class="col mobile-clear">
        <%= label :last_4, "Last four digits", class: "small bold block mb1" %>
        <%= text_field_tag 'donor_verification[last_4]', nil, placeholder: "Last 4 Digits", style: "width: 140px;", :autocomplete => "off" %>
        <a class="ss-icon ss-help tooltip relative" title="<div style='width: 300px'>The last 4 digits of the credit card you used for #{CONFIG[:name]}.</div>"></a>
      </div>
    </div>
  <% end %>

  <p class="error"></p>

  <%= submit_tag "Confirm cancellation", class: "button-solid button-green" %>

<% end %>

app/views/subscribers/show/_donations.html.erb
<h4 class="bold">Donations</h4>

<% if current_donor.gift && current_donor.gift.active? %>
  <p class="mb1">This is a gift that started on <%= current_donor.gift.start_on.to_s(:short_name) %><%= " and #{current_donor.gift.active? ? "ends" : "ended"} on #{current_donor.gift.finish_on.to_s(:short_name)}" unless current_donor.gift.infinite? %>.</p>
<% elsif current_donor.failed? && failed_donation = current_donor.donations.failed.first %>
  <p class="mb1">Your last $30 donation <em>failed</em> on <%= failed_donation.failed_at.to_date.to_s(:short_name) %>.</p>
<% elsif last_donation = current_donor.last_executed_donation %>
  <p class="mb1">Your last $30 donation was on <%= last_donation.executed_at.to_date.to_s(:short_name) %>.</p>
<% end %>
<% if !current_donor.active? && !current_donor.failed? %>
  <p class="mb1">Your donations ended on <%= current_donor.finished_on.to_s(:short_name) %>.</p>
<% end %>
  <p class="mb2">You have donated to <strong class="bold"><%= current_donor.nonprofits_donated_to.count %></strong> nonprofits so far. <%= link_to "See the full list", donations_subscriber_path(current_subscriber) %></p>

<% if current_donor.gift.present? %>
  <% # show anything here? %>
<% elsif current_donor.cancelled? && current_donor.active? %>
  <%= render "subscribers/show/uncancel" %>
<% elsif current_donor.active? %>
  <%= link_to "Change billing details", edit_donor_url(current_donor.subscriber), class: "small bold green no-wrap mr2" %>
  <br/>
  <%= render "subscribers/show/cancel" %>
<% elsif current_donor.failed? %>
  <%= link_to "Click here to fix!", edit_donor_url(current_donor.subscriber) %>
<% else %>
 <%= link_to "Signup to donate again!", donate_url(email: current_subscriber.email) %>
<% end %>

app/views/subscribers/show/_gifts.html.erb
<h4 class="bold">Gifts</h4>

<%- if current_subscriber.given_gifts.present? -%>
<ul class="bulleted-list">
<% current_subscriber.given_gifts.each do |gift| %>
  <li>
    <h4 class="mb0"><strong class="bold">$<%= gift.donor.donations.sum(:amount) %></strong> given to <strong class="bold"><%= gift.recipient_name %></strong> <span class="grey-mid">(<%= "#{gift.recipient_email}" %>)</span></h4>
    <p class="mb0">From <%= gift.start_on.to_s(:short_name) %> until <%= gift.infinite? ? "forever" : gift.finish_on.to_s(:short_name) %></p>
  </li>
<% end %>
</ul>
<%- else -%>
<p class="mb0">You haven’t given any gifts yet.</p>
<%- end -%>

app/views/subscribers/show/_info.html.erb
<%= form_for @current_subscriber, html: {autocomplete: "on"} do |s| %>
  <%# Hide this for now until there is a donor page %>
  <% fields_for :donor, @current_subscriber.donor do |d| %>
    <div class="mt2">
      <%= d.label :public_name, "Donor name", class: "bold" %>
      <div class="form-field half-width">
        <%= link_to "edit", "#", class: "right edit-field" %>
        <span class="display-name"><%= @current_subscriber.donor.card.name %></span>
        <%= d.text_field :public_name, placeholder: "Display name (Optional. To list you as an awesome donor.)", autocompletetype: "given-name", class: "hide" %>
      </div>
    </div>
  <% end if @current_subscriber.donor && @current_subscriber.donor.active? %>

  <h4 class="bold">Email</h4>

  <% if @current_subscriber.errors.present? %>
    <p><%= @current_subscriber.errors.full_messages.to_sentence.html_safe %></p>
  <% end -%>

  <% if @current_subscriber.active? %>

    <% if @current_subscriber.donor.try(:failed?) %>
      <p class="mb1">We've halted your daily emails because your last donation failed. <%= link_to "Click here to fix!", edit_donor_url(current_donor.subscriber) %></p>
    <% else %>
      <p class="mb1">You’re getting the daily email at <%= @current_subscriber.email %>.</p>
      <%= link_to "Unsubscribe", unsubscribe_subscriber_url(@current_subscriber), method: :put, data: {confirm: "Sure you want to unsubscribe?"}, class: "bold small mr2 red" %>
    <% end %>
  <% else %>
    <p class="mb2">You’re <strong class="bold red">not getting</strong> our daily email at <%= @current_subscriber.email %>.</p>
    <% button_text = @current_subscriber.never_subscribed? ? "Subscribe to the daily email" : "Resubscribe to the daily email" %>
    <%= link_to button_text, resubscribe_subscriber_url(@current_subscriber), method: :put, class: "button-solid button-green mr2" %>
  <% end %>

  <button class="text-button bold small green edit-field" data-toggles="subscriber_show_email">Change email</button>

  <div class="hide mt1" id="subscriber_show_email">
    <%= s.text_field :email, placeholder: "Email Address", autocompletetype: "email", size: 30, class: "clearfix small-input mobile-full-width fit mt1" %>
    <%= submit_tag "Save", class: "submit button-solid button-green mobile-full-width mt1" %>
  </div>
<% end -%>

app/views/subscribers/show/_uncancel.html.erb
<div class="flag">
  <div class="flag-body pr2">
    <div class="no-margin small">
      You cancelled future donations.
      <div class="mobile-inline">Would you like to undo?</div>
    </div>
  </div>
  <div class="flag-img no-wrap">
    <%= link_to "Restart donations!", uncancel_donor_url(@current_subscriber), class: "js-form-link button-solid button-green", :'data-form-id' => "restart-future-donations-form" %>
  </div>
</div>

<%= form_tag uncancel_donor_url(@current_subscriber), method: :put, id: "restart-future-donations-form", style: "display: none", class: "js-form mt4" do %>

  <% if auth_method != :card %>
    <p>To restart donations, please verify your credit card info:</p>

    <div class="row verification">
      <div class="col">
        <%= label :exp_month, "Credit card expiration", class: "small bold block mb1" %>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_month]', options_for_select((1..12).to_a) %>
          <span class="ss-icon ss-dropdown"></span>
        </div>
        <div class="select-container mb1 mr1 left">
          <%= select_tag 'donor_verification[exp_year]', options_for_select((Time.zone.now.year..10.years.from_now.year)) %>
          <span class="ss-icon ss-dropdown"></span>
        </div>
      </div>
      <div class="col mobile-clear">
        <%= label :last_4, "Last four digits", class: "small bold block mb1" %>
        <%= text_field_tag 'donor_verification[last_4]', nil, placeholder: "Last 4 Digits", style: "width: 140px;", :autocomplete => "off" %>
        <a class="ss-icon ss-help tooltip relative" title="<div style='width: 300px'>The last 4 digits of the credit card you used for #{CONFIG[:name]}.</div>"></a>
      </div>
    </div>
  <% end %>

  <p class="error"></p>

  <%= submit_tag "Confirm donation restart", class: "button-solid button-green" %>

<% end %>