config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
    end
  end
  resources :gifts, param: :guid, only: [:update, :new, :create] do
    member do
      get 'convert'
    end
    collection do
      get 'exists'
      get 'thanks'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'add_favorite/:nonprofit_id', to: redirect('/subscribers/%{guid}/favorites/%{nonprofit_id}/add')
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end

    resources :favorites,     controller: 'subscriber/favorites',
                              as: :favorites,
                              only: [:index, :destroy, :create] do

      get 'add',          action: :create, as: :add, on: :member
    end
  end

  resources :newsletters do
    get :preview, on: :collection
  end
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users

  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  get  'donate',           to: 'donors#new',         as: :donate
  post 'donate',           to: 'donors#create'
  get  'gift',             to: 'gifts#new',          as: :gift_page
  post 'gift',             to: 'gifts#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"
  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers do
      member do
        put :resend_newsletter
      end
    end
    resources :stats
    resources :payouts, only: [:index, :create]
    resources :newsletters do
      member do
        get :preview
        post :send_preview
        get :donor_generated
        get :subscriber_generated
      end
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_filter :authenticate_user!

  def index
    today = Time.zone.now
    @dates = {
      "Today" => today.strftime("%Y-%m-%d"),
      "Tomorrow" => (today + (3600 * 24)).strftime("%Y-%m-%d"),
      "Day After Tomorrow" => (today + (3600 * 24 * 2)).strftime("%Y-%m-%d")
    }
    @nonprofits = Nonprofit.is_public.featured_from(Time.zone.now.to_date + 1.day).limit(16)

    if Nonprofit.is_public.for_today.present?
      @todays_nonprofit = Nonprofit.is_public.for_today
    else
      @todays_nonprofit = Nonprofit.is_public.for_next_possible_day.first || Nonprofit.new(name: "No Nonprofit for Today", blurb: "n/a", description: "n/a", newsletter: Newsletter.new)
    end

    @subscriber = Subscriber.new
  end

  def donate
  end

  def wall_calendar
  end

  def legal
  end

  def faq
  end

  def contact
  end

  def send_feedback
    params[:email] = params[:email].to_s
    params[:message] = params[:message].to_s

    if params[:email] !~ Devise.email_regexp
      flash[:alert] = "Please enter a valid email address."
      render :contact
    elsif params[:message].blank?
      flash[:alert] = "Please enter a message to send."
      render :contact
    else
      SendFeedbackJob.new(params[:email], params[:message]).save
      flash[:notice] = "Thanks! We'll look at your message in a bit."
      redirect_to root_url
    end
  end

  def calendar
    @page_title = "Calendar"

    # TODO better solution than a rescue fallback here
    @date = Date.parse(params[:date]) rescue Date.today
    @future_nonprofits = Nonprofit.is_public.featured_from(@date).limit(31)
    @past_nonprofits = Nonprofit.is_public.featured_reverse_from(@date).limit(1)

    @subscriber = Subscriber.new
  end

  def share
    @full_url = params[:url]
    if @full_url
      @full_url += "&"
    else
      @full_url = [root_url, '?'].join('') if !@full_url
    end
    params.each do |k,v|
        @full_url += "#{k}=#{v}&" if ["redirect_uri", "href", "app_id", "display"].include?(k)
    end
    render :layout => false
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_get-involved.html.erb
<section id="get-involved" class="section">
  <div class="clearfix centered">
    <p class="big_type">Learning about amazing nonprofits isn’t easy.<br/><b class="green"><%= CONFIG[:name] %> makes is simple.</b></p>
    <div class="col col-6 pt2 pb2">
      <p><b>Get the email for free</b></p>
      <p class="mb2">Get our awesome tiny daily newsletter for free, no strings attached. The more awesome nonprofits you know about, the better. Knowledge is power! Signup in 10 seconds.</p>
      <p><%= link_to "Get the free newsletter", subscribe_path, :class => "button-outline button-green" %></p>
    </div>
    <div class="col col-6 pt2 pb2">
      <p><b>Become a donor</b></p>
      <p class="mb2">Each day, you’ll get our tiny daily newsletter about the amazing nonprofit that you and all the other donors are supporting that day. 100% tax-deductible for US residents.</p>
      <p>
        <%= link_to donate_path, class: "button-solid button-green" do %>
          <span class="border">Donate $1 a day</span>
        <% end %>
      </p>
    </div>

    <% if controller.controller_name != "site" %>
      <div class="clear"></div>
      <p class="pt4 centered">Want to learn more about <%= CONFIG[:name] %>? <%= link_to "Click Here", root_url %>.</p>
    <% end %>
  </div>
</section>

app/views/site/calendar.html.erb
<article id="content" class="bg-grey-light">
  <section id="intro" class="hero-calendar" data-0="opacity: 1;" data-400="opacity: 0;">
    <div class="container p2" data-0="top: 0px;" data-400="top: -40px;">
      <div class="row">
        <div class="col-center col-8">
          <div class="pt6 pb6">
            <h2 class="white no-margin">Everyone knows about the Red Cross, but what other nonprofits are doing great work?</h2>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div class="js-calendar-pagination-hide relative">

    <section id="calendar" class="js-add-dropshadow">
      <div class="container pl2 pr2 pt6 pb2">
        <div class="row">
          <div class="col-center col-8">

            <h4 class="bold no-margin pb3">Our calendar</h4>

            <p>We'll always have (at least) the next 60 featured nonprofits on this page. Come back to see the future anytime!</p>
            <p><%= link_to "See our full selection criteria", faq_path(anchor: "calendar") %> or browse our calendar of nonprofits below.</p>

          </div>
        </div>
      </div>
    </section>
  </div>

  <section id="nonprofits" class="bg-grey-light">
    <div class="container pt4 pb2 pl2 pr2 clip mobile-no-padding">
      <% if @future_nonprofits.present? %>
        <% @future_nonprofits[0, 30].in_groups_of(2, false).each_with_index do |nonprofit_row, index| %>
          <div class="row">
            <% nonprofit_row.each do |nonprofit| %>
              <div class="non-profit tablet-col tablet-col-6 mb4">
                <div class="non-profit-card-image bg-grey bg-cover bg-center" style="background-image: url(<%= nonprofit.photo.url(:medium)%>)"></div>
                <div class="bg-white p3">
                  <h3><%= nonprofit.name %></h3>
                  <h5 class="bold mb2">
                    <% if nonprofit.featured_on == Time.zone.now.to_date %>
                      Featured nonprofit for today.
                    <% elsif nonprofit.featured_on < Time.zone.now.to_date %>
                      Featured on <%= nonprofit.featured_on.to_formatted_s(:long_ordinal) %>
                    <% else %>
                      Will be featured on <%= nonprofit.featured_on.to_formatted_s(:long_ordinal) %>
                    <% end %>
                  </h5>
                  <% if nonprofit.description.length >= 250 %>
                    <div class="js-read-more">
                      <div class="js-read-more-hide">
                        <p><%= truncate(nonprofit.description, length: 250, omission: "... ") { link_to "Read more", nonprofit_url(nonprofit), class: "green no-wrap js-read-more-link" } %></p>
                      </div>
                      <div class="js-read-more-show hide">
                        <p><%= nonprofit.description %></p>
                        <p class="small"><%= link_to_nonprofit(nonprofit, target: "_blank") %></p>
                      </div>
                    </div>
                  <% else %>
                    <p><%= nonprofit.description %></p>
                    <p class="small"><%= link_to_nonprofit(nonprofit, target: "_blank") %></p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="pt2 pb4 centered" id="calendar_nav_links"
          data-date="<%= @date %>"
          data-previouspage="<%= (@date - 30.days) if @past_nonprofits.present? %>"
          data-nextpage="<%= @future_nonprofits.last.featured_on if @future_nonprofits.size > 30 %>">
        </div>
        <div class="mobile-show pb2">&nbsp;</div>
      <% end %>
    </div>
  </section>
</article>

app/views/site/contact.html.erb
<article id="content" class="table bg-cover pt8 pb8 mobile-no-padding" style="background-image: url(<%= asset_url("blurred-bg.jpg")%>)">

  <div class="table-cell">
    <div class="col-center col-8 bg-grey-light">
      <div class="p4">
        <h2 class="no-margin mb4">How can we help?</h2>
        <p class="mb4">If you want to cancel, <%= link_to "Manage account", "#authenticate-overlay", class: "js-modal-overlay-open" %><br/>
        Have general questions about <%= CONFIG[:name] %>, please read our <%= link_to "FAQ", faq_path %>.<br/>
        Other questions, press inquiries, or feedback? Please get in touch below.</p>
        <%= form_tag send_feedback_url, method: :post do -%>
          <div class="field <%= 'field_with_errors' if params[:email] %>">
            <%= label_tag :email, "Email" %>
            <%= text_field_tag :email, params[:email], size: 50, class: "full-width" %>
          </div>

          <div class="field <%= 'field_with_errors' if params[:message] %>">
            <%= label_tag :message, "Message", value: params[:message] %>
            <%= text_area_tag :message, params[:message], rows: 8, cols: 70, class: "full-width" %>
          </div>

          <p><%= submit_tag "Send", class: "button-solid button-green button-big" %></p>
        <% end -%>
      </div>
    </div>

  </div>

</article>

app/views/site/faq.html.erb
<section id="content" class="bg-grey-light pb6">
  <div class="header-shim"></div>
  <div class="container pl2 pr2">
    <div class="col-center col-8">
      <div class="mb4">
        <h3 class="bold mb2">What is <%= CONFIG[:name] %>?</h3>
        <p><%= CONFIG[:name] %> is a simple new way for people to discover and support nonprofits that do great work.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How does <%= CONFIG[:name] %> work?</h3>
        <p>Every day we feature one amazing nonprofit. Everyone (who’s signed up) automatically donates a dollar to that featured nonprofit. No daily decisions to make, no customization &mdash; every day we’re all supporting the featured nonprofit, together.</p>
        <p>Every day, we send out a simple email about the featured nonprofit we’re all supporting. These emails are an incredibly easy way to be introduced to great nonprofits. <%= link_to "#subscribe-overlay", class: "js-modal-overlay-open" do %>We also offer these daily emails to anyone for free<% end %>.</b></p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Who is <%= CONFIG[:name] %> for?</h3>
        <p><%= CONFIG[:name] %> is for anyone who wants to be more engaged with nonprofits. Finding great organizations can be difficult, and many of us are busier than ever. We wanted to make it easier for people to both discover and support great nonprofits.</p>
        <p>At its heart, <%= CONFIG[:name] %> is about discovery. We hope that our daily emails will be a gateway for people to give directly, volunteer for, or simply learn more about a variety of great organizations and the problems they’re trying to solve. A public more fluent in nonprofits and their work is really exciting.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">If I donate, will my credit card be charged $1 a day?</h3>
        <p>Nope. Donors are charged on a monthly cycle: $30 every 30 days. It keeps things simple and minimizes credit card fees.</p>
        <div class="divider"></div>
      </div>

      <!-- FOR ANCHOR LINK-->
      <div id="calendar"></div>

      <div class="mb4">
        <h3 class="bold mb2">Can I see the calendar of the nonprofits you’ll be featuring?</h3>
        <p>Yes! <%= link_to "Our calendar", calendar_path(ref: "faq") %> will always show (at least) the next 60 days of nonprofits.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">What is your selection criteria for nonprofits?</h3>
        <p> ... text goes here about selection criteria ... </p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Can I opt out of donating to certain nonprofits?</h3>
        <p>No. We’ve chosen to keep things simple to start. And we hope that instead of feeling a need to skip nonprofits that might not excite you, you’ll choose to go the other way: learn more, give more, and engage further with those that really grab you.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Can I suggest a nonprofit?</h3>
        <p>Yes! We would love to hear from you. <a href="https://..." target="_blank">Drop us a line</a>.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Are donations tax deductible?</h3>
        <p>All donations on <%= CONFIG[:name] %> are 100% US tax deductible. You'll get an email receipt when your credit card is charged.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How do donations get from <%= CONFIG[:name] %> to the nonprofits?</h3>
        <p><%= CONFIG[:name] %> distributes funds directly to each of our featured nonprofits within 30 days of feature.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How do I cancel once I’ve started donating?</h3>
        <p>We make it easy, with links to cancel from every daily email. Once you cancel you won’t be charged again, but your last $30 donation will still be distributed to the 30 nonprofits from the date of last donation.</p>
        <p>Even if you stop being a donor, you can still continue to receive our daily email for free!</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Am I going to get mail or email from nonprofits?</h3>
        <p>No. Your donations are processed anonymously. Your name, address, and email are not shared with nonprofits. You can always sign up for more info on any nonprofit’s website.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Will you ever repeat the same nonprofits?</h3>
        <p>At some point, we may repeat nonprofits &mdash; particularly, those featured in the early days, when fewer people were signed up. We have many hundreds to feature first, though, and we are always looking for more to consider. Know an organization doing good work? <a href="https://..." target="_blank">Suggest a nonprofit</a>.</p>
        <div class="divider"></div>
      </div>

      <div id="gifting"></div>

      <div class="mb4">
        <h3 class="bold mb2">I'd like to donate to <%= CONFIG[:name] %> as a gift to somebody else. Can I?</h3>
          <p><%= link_to "Definitely", gift_page_url(ref: "faq") %>. <%= CONFIG[:name] %> makes a great gift for anybody who wants to support cool causes or learn a little more about amazing nonprofits. You can gift somebody 30 days, 90 days, or on a continuing basis — it’s up to you!</p>

        <div class="divider"></div>
      </div>

      <div class="mb4">
        <h3 class="bold mb2">If I gift somebody <%= CONFIG[:name] %>, how will I be charged?</h3>

        <p>Give a gift of 30 days and we’ll charge you $30 at check-out. Easy! For a $90 gift, we will charge you $30 every 30 days, until the gift period is over. (A total of three $30 charges.) For a continuing gift, we will charge you just like any other donor: $30 every 30 days. You can cancel your gift anytime. Your gift is 100% US tax deductible.</p>
        <div class="divider"></div>
      </div>

      <div class="mb4">
        <h3 class="bold mb2">I'm a gift recipient! What happens now?</h3>

        <p>That’s great. Every day, a dollar will be donated to our day’s featured nonprofit in your name. You’ll also receive our daily email, telling you a little bit more about that organization’s mission. We hope is you’ll be inspired to explore each nonprofit further — by volunteering, continuing to spread the word, or giving directly.</p>
        <div class="divider"></div>
      </div>

      <div class="mb4">
        <h3 class="bold mb2"> Somebody gifted me <%= CONFIG[:name] %>, but my time is almost up! How can I become a full-time donor?</h3>
        <p>You can become a donor by clicking the “Become Donor” button from any daily email you receive. We'll pre-populate the donate form with your name and email. All you need to do is add your payment information. Easy!</p>
        <div class="divider"></div>
      </div>

      <div class="mb4">
        <h3 class="bold mb2">I'm a gift recipient, but I don't want to receive the daily emails. Can I unsubscribe?</h3>
        <p>You can. You can unsubscribe from any daily email just by clicking the "Unsubscribe" button.</p>
        <div class="divider"></div>
      </div>

      <div class="mb4">
        <h3 class="bold mb2">Is <%= CONFIG[:name] %> a nonprofit?</h3>
        <p> ... text about nonprofit status goes here ... </p>
        <div class="divider"></div>
      </div>
    </div>
  </div>
</section>

app/views/site/gifting.html.erb
<section id="hero" class="hero-home bg-grey-light table py4 relative clip">
  <div class="full-width">
    <div class="container py4 relative">
      <div class="gift-card p4 rounded">
        <%= image_tag "gift.svg", class: "block mt2 mb2 margin-auto mobile-hide" %>
        <%= image_tag "logo-dark.png", class: "block mb4 margin-auto mobile-hide gift-logo" %>
        <div class="gift-copy">
          <h2 class="centered">Hi Kilian</h2>
          <p>Every day, for the next 30 days a great, deserving charity will be given a $1 on your behalf.</p>
        </div>
        <form>
          <textarea placeholder="Add a personal message if you'd like" class="block"></textarea>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/site/index.html.erb
<%= render "nonprofits/newsletter_preview" %>

<section id="hero" class="hero-home bg-grey-light table py4 relative clip">
  <div class="table-cell full-width">
    <div class="container py4 relative centered">
      <div class="col-pre-1 col-post-1 pl2 pr2">
        <div class="pl8 pr8 mobile-no-padding">
          <%= image_tag "logo-dark.png", width: "140", class: "block mb4 margin-auto mobile-hide" %>

          <p class="big mb4">
            <span class="big">
              <%= CONFIG[:name] %> is a simple new way to discover and support amazing nonprofits. We feature one great organization every day, everyone automatically donates $1.
              <u class="pointer no-wrap js-hero-down">Learn more</u>.
            </span>
          </p>

          <div class="mb4">
            <%= link_to "Donate with #{donor_count} others", donate_path(ref: default_ref_tag), class: "button-solid button-green button-big mobile-block donate-button" %>


            <span class="mobile-hide pl1 pr1">or</span>
            <span class="mobile-show">&nbsp;</span>


            <%= link_to gift_page_url(ref: default_ref_tag), class: "button-outline button-grey button-big mobile-block" do %>
              <%= image_tag "gift.svg", width: 15, class: "inline-block", style: "margin-right: 5px;" %>
              <!-- Give as a gift -->
            <% end %>

            <div class="small pt3 grey">
              100% US tax-deductible
            </div>

          </div>
        </div>
      </div>
    </div>
    <%= image_tag "hero.jpg", width: "150%", class: "js-hero-image homepage-hero-image mobile-hide relative", :'data-0' => "top: 0px;", :'data-600' => "top: -40px;" %>

    <div class="centered">
      <b class="block py2 grey">As seen in:</b>
      <div class="mobile-hide">
        <%= image_tag "logos/homepage-logos.png", width: "80%", class: "opacity-50" %>
      </div>
      <div class="mobile-show">
        <%= image_tag "logos/homepage-logos-mobile.png", width: "90%", class: "opacity-50" %>
      </div>
    </div>
  </div>
</section>


<section id="support" class="js-learn-more-scroll-to table bg-grey pt8">
  <div class="table-cell pb8">
    <div class="py4 px6 white">
      <h1>Support</h1>
      <p class="big">Every day, we all give a dollar to the day's featured nonprofit. No daily actions &mdash; it's automatic.</p>
      <p class="big">Our (tiny) daily email will tell you about the nonprofit we’re all supporting together that day.</p>
      <a href="#email-preview" class="js-modal-overlay-open bold white">Preview today's email</a>
    </div>
  </div>
  <div class="table-cell align-bottom mobile-hide">
    <div class="iphone relative clip">
      <div class="js-iphone-overlay iphone-overlay l50p bg-white full-height opacity-0 transition-all absolute clip">
        <%= image_tag(@todays_nonprofit.photo.url(:full), height: "240", class: "block relative mb2") %>
        <h5 class="bold centered">Today's nonprofit</h5>
        <h4 class="centered pl2 pr2"><%= @todays_nonprofit.name %></h4>
      </div>
      <%= image_tag "iphone-cropped.png", class: "block margin-auto js-iphone-image", width: "320" %>
    </div>
  </div>
</section>


<section id="selection" class="bg-grey-light table">
  <div class="table-cell calendar-bg">
    <div class="hide tablet-block">
      <div class="mobile-table full-height bg-black-40 p6">
        <div class="mobile-table-cell pt8 pb8">
          <h1 class="white">Amazing nonprofits</h1>
          <p class="big mb0">Our team hand picks each nonprofit we feature. We select innovative, high impact organizations that are well-rated by trusted, publicly available resources like Guidestar and Charity Navigator.</p>
          <p class="big mb0">These nonprofits are doing great work all over the world. We think you’ll love learning about them.</p>
          <%= link_to calendar_path(ref: default_ref_tag), class: "bold white no-decoration" do %>
            <span class="ss-icon ss-calendar"></span>
            <u>See our calendar</u>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="table-cell tablet-hide p6">
    <div class="pt8 pb8">
      <h1>Amazing nonprofits</h1>
      <p class="big mb0">Our team hand picks each nonprofit we feature. We select innovative, high impact organizations that are well-rated by trusted, publicly available resources like Guidestar and Charity Navigator.</p>
      <p class="big mb0">These nonprofits are doing great work all over the world. We think you’ll love learning about them.</p>
      <%= link_to calendar_path(ref: default_ref_tag), class: "bold no-decoration" do %>
        <span class="ss-icon ss-calendar"></span>
        <u>See our calendar</u>
      <% end %>
    </div>
  </div>
</section>


<section class="table bg-white js-add-dropshadow">

  <div class="table-cell p6">
    <div class="pt8 pb8">
      <h1>Discover</h1>
      <p class="big">
        <%= link_to "Anyone can get our daily emails for free!", "#subscribe-overlay", class: "js-modal-overlay-open" %>
        Why? They can be a gateway for all of us to learn more about great nonprofits, inspiring us to support and engage with these organizations further.
      </p>
    </div>
  </div>
  <div class="table-cell bg-black mobile-hide">
    <div class="mobile-table full-height">
      <% @nonprofits.in_groups_of(4, false).each_with_index do |nonprofit_row, index| %>
        <div class="mobile-table-row">
          <% nonprofit_row.each do |nonprofit| %>
            <div class="mobile-table-cell bg-cover bg-center opacity-50" style="height: 170px; background-image: url(<%= nonprofit.photo.url(:medium)%>)">&nbsp;</div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</section>

<section id="power-of-the-masses" class="bg-green" data-200-top-top="background-color: rgb(102,102,102);" data-300-top-bottom="background-color: rgb(79,187,126);">
  <div class="container centered pl2 pr2 pt8 pb8">
    <div class="col-center col-10 tablet-full-width mobile-no-padding">
      <div class="pt8 pb8">
        <h2 class="white no-margin">$1 a day can really help. Every 3,000 donors is more than a million dollars a year to nonprofits!</h2>
      </div>
    </div>
  </div>
</section>


<section class="pt8 pb4 centered bg-grey-light">
  <div class="container p2">
    <div class="row">
      <div class="tablet-col tablet-col-4 mb4" data-650-top-top="opacity: 0;" data-650-top-bottom="opacity: 1;">
        <%= image_tag "site/icon-30-days.svg", width: 100, class: "mb2" %>
        <h3>$30 monthly, US tax-deductible.</h3>
        <div class="pl2 pr2 tablet-portrait-extra-padding">
          <p>Donors are charged $30 every 30 days. We make it easy to cancel, and all donations are 100% US tax-deductible.</p>
        </div>
      </div>
      <div class="tablet-col tablet-col-4 mb4" data-600-top-top="opacity: 0;" data-600-top-bottom="opacity: 1;">
        <%= image_tag "site/icon-nfg.svg", width: 100, class: "mb2" %>
        <h3>Anonymously processed.</h3>
        <div class="pl3 pr3 tablet-portrait-extra-padding">
          <p>To spare your inbox, your email isn’t shared with nonprofits. You can always sign up for more info on any nonprofit’s website.</p>
        </div>
      </div>
      <div class="tablet-col tablet-col-4 mb4" data-550-top-top="opacity: 0;" data-550-top-bottom="opacity: 1;">
        <%= image_tag "site/icon-nonprofit-too.svg", width: 100, class: "mb2" %>
        <h3>We’re a nonprofit too!</h3>
        <div class="pl3 pr3 tablet-portrait-extra-padding">
          <p><%= CONFIG[:name] %> makes no money, in any way, from donations on this site. <%= CONFIG[:name] %> was built by a team of (almost entirely) volunteers.</p>
        </div>
      </div>
    </div>
    <div class="pt4 pb2">
      <%= link_to "Become a donor!", donate_path(ref: default_ref_tag), class: "button-solid button-green button-big mobile-block mb1" %>
      <span class="inline-block pl2 pr2 mobile-hide">or</span>
      <%= link_to "Learn more", faq_path(ref: default_ref_tag), class: "button-outline button-grey button-big mobile-block mb1" %>
    </div>
  </div>
</section>

app/views/site/share.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div id="site_share">
    <code id="url" style="display:none;"> <%= @full_url %> </code>
    <!-- <code> <%= @full_url %> </code> -->
  </div>

  <%= javascript_include_tag "share" %>
</body>
</html>