config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
    end
  end
  resources :gifts, param: :guid, only: [:update, :new, :create] do
    member do
      get 'convert'
    end
    collection do
      get 'exists'
      get 'thanks'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'add_favorite/:nonprofit_id', to: redirect('/subscribers/%{guid}/favorites/%{nonprofit_id}/add')
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end

    resources :favorites,     controller: 'subscriber/favorites',
                              as: :favorites,
                              only: [:index, :destroy, :create] do

      get 'add',          action: :create, as: :add, on: :member
    end
  end

  resources :newsletters do
    get :preview, on: :collection
  end
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users

  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  get  'donate',           to: 'donors#new',         as: :donate
  post 'donate',           to: 'donors#create'
  get  'gift',             to: 'gifts#new',          as: :gift_page
  post 'gift',             to: 'gifts#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"
  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers do
      member do
        put :resend_newsletter
      end
    end
    resources :stats
    resources :payouts, only: [:index, :create]
    resources :newsletters do
      member do
        get :preview
        post :send_preview
        get :donor_generated
        get :subscriber_generated
      end
    end
  end
end

app/views/layouts/partials/_admin_bar.html.erb
<div class="admin_bar small white bg-black-80 fixed full-width b0 l0 z-index-max">
  <div class="container p2">
    <div class="clearfix">
      <p class="signed_in_as left no-margin">
        Signed in as <%= link_to current_user.email, edit_user_registration_path, class: "white" %><br />
      </p>
      <nav class="links right">
        <%= link_to_unless_current "Nonprofits", admin_nonprofits_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <% if @nonprofit and !@nonprofit.new_record? %>
          <%= link_to "Edit Nonprofit", edit_admin_nonprofit_url(@nonprofit.id), class: "white" %>
          &nbsp;&nbsp;&nbsp;
        <% end %>
        <%= link_to_unless_current "Stats", admin_stats_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Emails", "/admin/mailers", class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Subscribers", admin_subscribers_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Donors", admin_donors_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Payouts", admin_payouts_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Delayed Jobs", admin_delayed_jobs_url, class: "white" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Logout", destroy_user_session_url, method: :delete, class: "white" %>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/partials/_cta_know_more.html.erb
<aside class="bg-pattern white"><div class="px-gutter py6 centered col-max-10 col-center">
  <div class="big">
    <p class="mb0 bold"><%= CONFIG[:name] %> is a simple new way to discover and support amazing nonprofits.</p>
    <p class="mb3">We feature one great organization every day, everyone automatically donates&nbsp;$1.</p>
  </div>
  <p class="mb0"><%= link_to "Learn More", root_path, class: "button-outline button-white button-hover-black" %></p>
</div></aside>

app/views/layouts/partials/_footer.html.erb
<footer class="main bg-grey-light clip"><div class="container p2">

  <%- if !@hide_plane -%>
  <div class="py4">
    <%= image_tag "plane.svg", width: 281, class: "fit relative", "data-800-top" => "left: 0px;", "data-200-top" => "left: 800px" %>
  </div>
  <%- end -%>

  <div class="links tablet-center row">
    <div class="tablet-col grey"><span class="small mobile-block py1">&copy; <%= Time.zone.now.year %> <%= CONFIG[:name] %></span></div>
    <div class="tablet-col-right">
      <span class="mobile-block py1">
        <%= link_to "Home", root_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey #{'hide' if controller.controller_name == 'site' and controller.action_name == 'index'}" %>
        <%= link_to "FAQ", faq_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%= link_to "Contact", contact_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%= link_to "Terms & Privacy", legal_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%- if current_subscriber? -%>
        <%= link_to "Account", subscriber_path(current_subscriber), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%- else -%>
        <%= link_to "Manage account", "#authenticate-overlay", id: "authenticate_link", class: "small js-modal-overlay-open no-wrap inline-block pr2 pl1 pb1 grey" %>
        <%- end -%>
      </span>
      <span class="mobile-show big py1">
        <a href="https://twitter.com/<%= CONFIG[:twitter_username] %>" target="_blank" class="inline-block grey no-decoration color-twitter-hover"><span class="ss-icon ss-social-circle ss-twitter transition-all"></span></a>
        <a href="https://www.facebook.com/<%= CONFIG[:facebook_username] %>" target="_blank" class="inline-block grey no-decoration color-facebook-hover"><span class="ss-icon ss-social-circle ss-facebook transition-all"></span></a>
      </span>
      <span class="mobile-hide py1">
        <a href="https://twitter.com/<%= CONFIG[:twitter_username] %>" target="_blank" class="inline-block grey no-decoration color-twitter-hover"><span class="ss-icon ss-social-circle ss-twitter transition-all"></span></a>
        <a href="https://www.facebook.com/<%= CONFIG[:facebook_username] %>" target="_blank" class="inline-block grey no-decoration color-facebook-hover"><span class="ss-icon ss-social-circle ss-facebook transition-all"></span></a>
      </span>
    </div>
  </div>
</div></footer>
<% if current_user.try(:is_admin?) %>
  <div class="footer_prop"></div>
<% end %>

<%= render 'donors/authenticate_form' %>

app/views/layouts/partials/_head.html.erb
<script src="//cdn.optimizely.com/js/2495470497.js"></script>
<title>
  <%= (@page_title ? "#{@page_title} — #{CONFIG[:name]}": CONFIG[:name]) %>
</title>
<link href="/favicon.png" type="image/png" rel="icon" />
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<%= meta_tags %>
<%= csrf_meta_tags %>

<script type="text/javascript">
  WebFontConfig = { fontdeck: { id: '37871' } };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
    '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })();
</script>

<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application", async: !true %>
<%= javascript_include_tag "donor_test",  async: !true unless Rails.env.production? %>
<%= javascript_include_tag "admin",       async: !true if current_user.try(:is_admin?) %>

<% if @require_stripe_js %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey("<%= STRIPE[:publishable_key] %>");
  // ...
</script>
<% end %>

app/views/layouts/partials/_header.html.erb
<% unless @hide_header_shim %>
  <div class="header-shim"></div>
<% end %>

<% unless @hide_donate_button %>
  <div class="js-join-overlay modal-overlay fixed">
    <div class="modal-bg modal-overlay-dark"></div>
    <div class="modal-bg modal-overlay-dark"></div>
    <a href="#" class="js-modal-overlay-close modal-overlay-close z-index-2"><%= image_tag "x-white.svg", width: 20, height: 20 %></a>
    <div class="full-height mobile-table relative">
      <div class="mobile-table-cell centered p4 js-interior">
        <%= link_to donate_path(ref: "header"), class: "bold white no-decoration" do %>
          <p class="big mb2">Donate with <%= donor_count %> others</p>
          <span class="button-solid button-green button-big">Become a donor</span>
        <% end %>
        <div class="border-top-white mt4 mb4"></div>
        <%= link_to subscribe_path(ref: "header"), class: "bold no-decoration white" do %>
          <p class="big mb2">Get the email for free</p>
          <span class="button-outline button-white button-big">Subscribe</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<header class="primary-header bg-white fixed t0 max-width-wrapper z-index-2 full-width"
  <% if controller.controller_name == "site" and controller.action_name == "index" %>
  data-0="top: -100px" data-100p="top: 0px"
  <% end %>
  >

  <div class="container p2">
    <div class="flag">
      <div class="flag-img">
        <div class="flag">
          <div class="flag-img">
            <%= render "modules/logo_link", theme: :dark %>
          </div>
          <div class="flag-body">
            <h4 class="no-margin pt1 pb1 pl3 ml3 border-left desktop-show">Discover &amp; support amazing nonprofits</h4>
            <% unless @hide_donate_button %>
              <div class="mobile-show align-right">
                <%= link_to "Join", donate_path(ref: "header"), class: "button-solid button-green js-join-button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% unless @hide_donate_button %>
        <div class="mobile-hide">
          <div class="flag-body align-right">
            <div class="flag">
              <% unless @hide_email_link %>
                <div class="flag-body pr2 no-wrap">
                  <%= link_to "#subscribe-overlay", class: "js-modal-overlay-open small" do %>
                  Get the email for free
                  <% end %>
                </div>
              <% end %>
              <div class="flag-img no-wrap">
                <%= link_to "Donate with #{donor_count} others", donate_path(ref: "header"), class: "button-solid button-green donate-button" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</header>

<%= render "subscribers/overlay" %>

app/views/layouts/partials/_scripts.html.erb
<% if CONFIG[:google_analytics_id] %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.asynck=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '<%= CONFIG[:google_analytics_id] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

<%# Don't include tracking scripts on new donor page %>
<% if page_id != "donors_new" && page_id != "donors_create" %>

  <!-- Facebook -->
  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= FACEBOOK[:app_id] %>',
        xfbml      : true,
        version    : 'v2.3'
      });
    };
    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

  <!-- Twitter -->
  <script>
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return t;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
  </script>

<% end %>